skyconfig/config.go
Allowing all request from different domain is helpful for getting start to do
real work in development, while the user can always restrict the request on
production deployment.
=> Make the CORSHost default to `*`

Godeps/Godeps.json, main.go, push/apns.go, push/apns_test.go, skydb/conn.go, skydb/mock_skydb/mock.go, skydb/pq/device.go, skydb/pq/device_test.go, skydb/skydbtest/skydbtest.go
This commit switch the underlying APNS library to
RobotsAndPencils/buford, which sends push notification to APNS
through HTTP/2 protocol. The new protocol provides immediate feedback
for each notification sent.
connects #47
=> Use HTTP/2 APNS protocol

main.go, pkg/server/plugin/plugin.go, pkg/server/skyconfig/config.go
In slave mode, features that are not multiple-instance-safe are diabled.
These features include pubsub, subscription and cron job. Running them
in multiple-instance environment will cause data loss (pubsub messages sent
to an instance not delivered to all clients) or unexpected behaviour (cron jobs
run more than once).
Slave mode can be activated with environment variable `SLAVE=1/YES/true`
(default is false). 
connects skygeario/skygear-server#103
connects skygeario/skygear-server#104
connects skygeario/skygear-server#105
=> Implement slave mode

docker-compose.yml
It will solve the first time init fails. The skygear-server will restart until
it works and user will see it up and running after the DB is finished init.
connect #145
=> Mark the skygear-server restart to always and remove redis

pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/broker_test.go
zmq broker don't accept non register plugin heartbeat. It will force the plugin
resend a proper Ready and go through the init process again.
refs #150
=> Fix fast restart of skygear-server result on worker stale

.travis.yml, Makefile, pkg/server/skydb/pq/migration/migration_test.go, pkg/server/skydb/pq/pq_test.go, pkg/server/skydb/pq/schema.go
The fix comes in multiple parts:
* Drop table when cleaning up test db connection, this will also drop
the db table change trigger.
* Wrap createTable/dropTable operation in a transaction.
* The pq part of the test suite has problem running with other parts,
so we run the pq part separately.
connects #182
=> Fix travis test

pkg/server/handler/recordutil.go
This only happens when saving multiple records with a
schema-incompatible record being latter than schema-compatible ones.
connects #140
=> Fix unable to detect schema conflict

glide.lock, glide.yaml, pkg/server/handler/recordutil.go, pkg/server/skydb/pq/conn.go, pkg/server/skydb/pq/schema.go, pkg/server/skydb/pq/types.go
* Add support for bigint db type
* Fix not enumerating all rows from database during record schema query
* Fix record schema cached even when there was an error querying record schema
* Update sqlx/libpq to latest version
connects #218
=> Fix various issues with creating user on sign up

main.go, pkg/server/handler/asset.go, pkg/server/handler/auth.go, pkg/server/handler/device.go, pkg/server/handler/me.go, pkg/server/handler/push.go, pkg/server/handler/record.go, pkg/server/handler/relation.go, pkg/server/handler/role.go, pkg/server/handler/schema.go, pkg/server/handler/subscription.go, pkg/server/handler/user.go, pkg/server/plugin/handler.go, pkg/server/plugin/lambda.go, pkg/server/plugin/plugin.go, pkg/server/plugin/plugin_test.go, pkg/server/plugin/transport.go, pkg/server/plugin/transportstate_string.go, pkg/server/preprocessor/plugin.go, pkg/server/router/model.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
=> Support plugin only request during plugin initialization

pkg/server/plugin/exec/process_test.go, pkg/server/plugin/http/http_test.go, pkg/server/plugin/transport.go, pkg/server/plugin/transport_test.go, pkg/server/preprocessor/auth.go, pkg/server/router/model.go
=> Put access_key_type to plugin request context

pkg/server/handler/file_test.go, pkg/server/handler/record.go, pkg/server/handler/record_test.go, pkg/server/handler/recordutil.go, pkg/server/plugin/exec/process_test.go, pkg/server/plugin/http/http_test.go, pkg/server/skydb/conn.go, pkg/server/skydb/mock_skydb/mock.go, pkg/server/skydb/pq/asset.go, pkg/server/skydb/skyconv/map.go
connect https://github.com/SkygearIO/skygear-SDK-JS/issues/164
The original code does not query assets at all, feels like intentionally leaving some fields blank to save a query, so this PR is not really fixing bug, but adding functionality.
=> Actually fetch assets data in query

pkg/server/skydb/skyconv/map.go
follow up of #287.
Making it compulsory will break old SDK and not necessary, since the server will
guess mimeType in Handler
=> Make content type optional at incoming JSON

main.go, pkg/server/handler/auth_test.go, pkg/server/handler/record_test.go, pkg/server/handler/recordutil.go, pkg/server/handler/schema.go, pkg/server/handler/schema_test.go, pkg/server/skydb/conn.go, pkg/server/skydb/mock_skydb/mock.go, pkg/server/skydb/pq/access_schema.go, pkg/server/skydb/pq/migration/069921d63218_add_default_access.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/skydbtest/skydbtest.go
connect https://github.com/SkygearIO/skygear-server/issues/309
Client side needs update as well
- JS https://github.com/SkygearIO/skygear-SDK-JS/pull/180
- iOS https://github.com/SkygearIO/skygear-SDK-iOS/pull/83
=> Make default ACL server-based

.gogocyclo, pkg/server/handler/record_test.go, pkg/server/handler/recordutil.go, pkg/server/skydb/record.go, pkg/server/skydb/skydbtest/skydbtest.go
recordSaveHandler (recordutil.go) did not check if the fetched
record is a new record or an existing record, causing the
originalRecordMap to contain incorrect data. This PR also removes
the need for a hot fix to populate new record fields.
=> Fix potential problem when saving new record

pkg/server/handler/query.go, pkg/server/handler/query_test.go, pkg/server/skydb/pq/builder/factory.go, pkg/server/skydb/pq/builder/predicate.go, pkg/server/skydb/pq/builder/predicate_test.go
This is caused by two problems: The query parser did not accept keypaths
with multiple components and the `_access` identifier in SQL is not
fully qualified.
=> Fix handler/query does not allow joined query

Makefile
This makes less pain to developer if the source can not build properly and the generated files would not be gone.
=> Move delete old generated mock files after go install

main.go, pkg/server/authtoken/jwt.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/common.go, pkg/server/handler/device.go, pkg/server/handler/me.go, pkg/server/handler/me_test.go, pkg/server/handler/record.go, pkg/server/handler/relation.go, pkg/server/handler/relation_test.go, pkg/server/handler/role.go, pkg/server/handler/subscription.go, pkg/server/plugin/handler.go, pkg/server/plugin/lambda.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/router/model.go, pkg/server/skydb/authinfo.go, pkg/server/skydb/authinfo_test.go, pkg/server/skydb/skydbtest/skydbmockutil.go, pkg/server/skydb/skydbtest/skydbtest.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
connect #393
need #421
- Update signup and login request to accept `auth_data`
- Update signup, login, add relation and query relation response to return user record
- Treat empty string value in `auth_data` as valid value, so it would not be purged
- `auth_data` is no longer restricted to string, if empty string is purged, then `0` and `false` would also be purged, which does not make sense
- Add InjectUserIfPresent preprocessor
Note:
`AUTH_RECORD_KEYS` is NOT implemented yet, the current implementation is equal to `AUTH_RECORD_KEYS=username,email`. Most likely, the next, and hopefully the last for the feature, PR would finish that.
=> New user profile design: auth request with auth data and response with user record

.travis.yml, scripts/docker-images/godev/Dockerfile
This is because the libzmq libraries installed in debian jessie
is too old for czmq 4.0.2. Upgrading to debian stretch solved the
problem.
The golang version is also upgraded to go1.8.3.
=> Fix unable to build working docker image

.env.example, main.go, pkg/server/handler/auth.go, pkg/server/handler/auth_disable_set.go, pkg/server/handler/device.go, pkg/server/handler/me.go, pkg/server/handler/record.go, pkg/server/handler/relation.go, pkg/server/handler/schema.go, pkg/server/handler/subscription.go, pkg/server/plugin/handler.go, pkg/server/plugin/lambda.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/router/errors.go, pkg/server/skyconfig/config.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
If the user is not allowed to access resource because of policies on user
data, such as password expiry, token expiry, disabled or not verified,
The preprocessor will still allow access if user is not required. Preprocessor
will not set AuthInfo in this case.
connects #554
=> Update logic for user checking in preprocessors

pkg/server/plugin/plugin.go
The error occur randomly when init multiple plugins.
The error logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-fix-perms: applying...
[fix-attrs.d] 01-fix-perms: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ln: failed to create symbolic link './node_modules': File exists
2018/07/03 04:05:09 Error in loading .env file
time="2018-07-03T04:05:09Z" level=info msg="Starting Skygear Server(v1.6.0-1-g0b2dac6)..." logger=main process=server
time="2018-07-03T04:05:09Z" level=debug msg="Version table …
```
=> Fix fatal error, concurrent map iteration and map write when init plugins

cmd/auth/main.go, pkg/auth/dependency/dependency.go, pkg/auth/handler/login.go, pkg/auth/provider/provider.go, pkg/core/db/db.go, pkg/core/handler/factory.go, pkg/core/server/server.go
Server should not aware of the dependency, while handler factory should.
Here we try to move the mount path information to handler instead of
main.go. It is because the where is mount related more to the business
logic of a handler than how the server boot.
connect #630
=> Move dependency logic to handler factory

cmd/auth/main.go, cmd/gateway/main.go, pkg/auth/handler/disable.go, pkg/auth/handler/login.go, pkg/auth/handler/me.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/core/handler/factory.go, pkg/core/inject/inject.go, pkg/core/logging/logging.go, pkg/core/logging/logging_test.go, pkg/core/logging/text_formatter.go, pkg/core/logging/value_formatters.go, pkg/core/middleware/requestid.go, pkg/core/server/server.go, pkg/gateway/config/config.go, pkg/gateway/db/pq/app.go, pkg/gateway/db/pq/store_exec.go, pkg/gateway/db/pq/types.go, pkg/gateway/provider/config.go
Try to bring back logging functionality to next, what I did in this pr.
- Move logging from v1 to next
- Add middleware that add request id to context
- Add `HandlerLogger` dependency
Question: The request id middleware is copied from v1, which will create request id and update the context. As I remember, we had discussion about the middleware should only update request header in next? So the old middleware implement may violate the rule? Or it is acceptable in this case?
=> next: Gear logging

pkg/auth/handler/disable.go, pkg/auth/handler/login.go, pkg/auth/handler/me.go, pkg/auth/handler/signup.go, pkg/auth/response/response.go, pkg/core/auth/authn/authn.go, pkg/core/auth/authn/resolver/default.go, pkg/core/auth/authn/resolver/masterkey.go, pkg/core/auth/authn/resolver/non_masterkey.go, pkg/core/auth/authz/authz.go, pkg/core/auth/authz/policy/accesskey.go, pkg/core/auth/authz/policy/authinfo.go, pkg/core/auth/authz/policy/compound.go, pkg/core/auth/authz/policy/disable.go, pkg/core/auth/authz/policy/everybody.go, pkg/core/auth/authz/policy/role.go, pkg/core/handler/api.go, pkg/core/handler/context/context.go, pkg/core/handler/factory.go, pkg/core/handler/handler.go, pkg/core/server/server.go
Move authz.PolicyProvider from handler to handler factory.
---
Update:
handler.Factory must implement authz.PolicyProvider, reason:
- Optional interface make debug hard, it's hard to trace if the policies are applied to one endpoint until test case or runtime.
- Authentication is mandatory already, so making authorisation mandatory seems also resonable.
- Adding `Allow everybody` policy is easy.
- Authorisation itself is stateless and lightweight, adding it to every handler should have very little performance hit.
=> next: Fix api handler bypassed authz policy

cmd/record/main.go, pkg/record/dependency/record/pq/schema.go, pkg/record/dependency/record/pq/tx_store.go, pkg/record/dependency/record/store.go, pkg/record/handler/schema_create.go, pkg/record/handler/schema_create_test.go, pkg/record/handler/schema_utils.go
connect #731 
Commit 5047e06 is fixing problem that occur after adding transaction to schema create handler, we didn't have this problem in v1 as we didn't have transaction in schema create handler.
The problem happens if we make query before the previous query cursor close, updated `GetRecordSchemas` to avoid this.
related issue: https://github.com/lib/pq/issues/635
=> next: schema create handler

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/gateway/config/config.go, pkg/gateway/model/plan.go, scripts/gateway/migrations/1541398893_add_record_enabled.down.sql, scripts/gateway/migrations/1541398893_add_record_enabled.up.sql
connects #755 
1. add `SKYGEAR_URL` to `TenantConfiguration`, this is used in auth gear to generate a request to record gear.
2. add `record_enabled` to `Plan` table, it helps gateway to know if it routes record request of an app to record gear.
=> next: add skygear url to tenant configuration

Makefile, tools/nextimportslint.go
connects #771
- currently, skygear next imports server pkg for `skyerr`, `logging` and other utilities, so the lint ignores import `server` temporarily.
=> Add lint check gear imports another gear

cmd/gateway/main.go, pkg/core/config/tenant.go, pkg/core/config/tenant_test.go, pkg/core/middleware/tenant.go, pkg/core/middleware/tenant_test.go, pkg/core/server/option.go, pkg/gateway/db/pq/app.go, pkg/gateway/db/pq/types.go
connect #791
- Default value and validation are for env and json config source only. Since we used msgp for transporting through request header, which is not the config source. The input and output will be the same and the default value and validation is not applied
- Allow static default by updating `NewTenantConfiguration`
- Allow a degree of flexible to update dynamic default in `AfterUnmarshal`
- SkygearIO/py-skygear#232 is not addressed here, since gear communicate is through public gateway now. And we may want to revisit in when we do cloud function and see if it is still valid.
=> next: Tenant config default

pkg/auth/dependency/sso/mock_provider.go, pkg/auth/dependency/userprofile/mock_store.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/sso.go
connects #841 
1. If app's authRecordKeys contains ['email'], then auto connect procedure will be executed.
2. If auto connect is executed, it will find corresponding password principal base on authData (which is a map contains provider email), if it finds one, then will use it as the user principal.
3. When signup a new user, and app's authRecordKeys contains ['email], it will generate an empty password principal as well.
=> next: SSO should support auto link existed user account

pkg/auth/handler/sso/config.go
When authorized_urls is empty, that means allow all urls. SDK assumes authorized_urls key
always exists. API should return empty array when it is empty.
=> next: update sso config api to always return authorized_urls, return empty array when it is empty.

pkg/core/sms/nexmo.go
connect #870 
Check the message report return from nexmo client, and return the error when fail to send sms
=> Fix nexmo sms sender error handling

pkg/server/skydb/pq/listener.go
connect #136
When the pq listener reconnected to server, and nil notification will be sent to the Listener.Notify channel.
Updated to handle the nil notification.
refs: https://godoc.org/github.com/lib/pq#NewListener
> // ListenerEventReconnected is emitted after a database connection has
> // been re-established after connection loss. The err argument of the
> // callback will always be nil. After this event has been emitted, a
> // nil pq.Notification is sent on the Listener.Notify channel.
To test it, stop the db and start it again
=> Fix server crash when receiving pq listener event=2

pkg/core/server/server.go
connect #810
Skip all middleware for healthz endpoint
We added tenant config decode middleware in all gear routes, which healthz endpoint should
not go through the same flow.
=> Fix gear /healthz endpoint

cmd/migrate/revisions/gateway/1554279410_remove_cloud_code_config.down.sql, cmd/migrate/revisions/gateway/1554279410_remove_cloud_code_config.up.sql, cmd/migrate/revisions/gateway/1554280667_rename_to_cloud_code_route.down.sql, cmd/migrate/revisions/gateway/1554280667_rename_to_cloud_code_route.up.sql, cmd/migrate/revisions/gateway/1554378292_remove_cloud_code_backend_url_default.down.sql, cmd/migrate/revisions/gateway/1554378292_remove_cloud_code_backend_url_default.up.sql, pkg/gateway/config/config.go, pkg/gateway/db/pq/cloudcode.go, pkg/gateway/handler/cloudcode.go
The table name `cloud_code` duplicated with that of skygear-controller, so table renamed to `cloud_code_route` and the table only contains routing data.
=> Update cloud code model

pkg/core/auth/session/provider_impl.go, pkg/core/auth/session/provider_impl_test.go
Non-ASCII characters in HTTP header value may have undefined behavior, and JSON may contains them.
ref #1010
=> Encode extra info JSON object in base64

cmd/gateway/main.go
CORS header should be set as soon as possible (i.e. a proxy backend has been matched), so that client can read the potential errors in response headers/body.
fix #1078
=> Fix incorrect timing for setting CORS headers

cmd/asset/main.go, pkg/asset/config/config.go, pkg/asset/handler/get.go, pkg/core/cloudstorage/s3.go
For local development purpose, it is easier to setup a minio server and use S3 backend of asset gear.
Also, when CORS headers is returned by storage backend, we should pass-through these headers directly in the reverse proxy. For asset gear in standalone mode, removing headers added by middleware would be enough. However for asset gear behind gateway, we'll need some way to instruct gateway to pass-through the CORS headers from asset gear (TODO).
=> Update asset gear config & behavior

pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/core/async/executor.go
connect #1142 
Signup handler enqueue the tasks before db transaction commit. And `VerifyCodeSendTask` will query the db for the user data, so the task may fail randomly due to user not found error. This PR updates the flow to enqueue tasks after db commit. We may have similar problems in another handlers, will check and open another PR if needed.
=> Fix signup verification email

pkg/core/http/cors.go, pkg/core/http/cors_test.go, pkg/gateway/handler/deployment_route.go
Static assets goes through many services:
```
Client -> Gateway (static asset) -> Gateway (asset gear) -> Asset Gear
```
Before this fix, some duplicated headers can be observed:
- Request ID (x2)
- Vary: Origin (x3)
=> Adjust static asset gateway proxying

pkg/auth/dependency/sso/auth_handler_html.go, pkg/auth/dependency/sso/callback_url.go, pkg/auth/dependency/sso/callback_url_test.go
=> Ignore query, fragment and trailing slash in validating callbackURL

.travis.yml
- Remove release step in travis deployment
- We used this to submit binary to github release page, we don't need this in next
- Run deploy github page in master branch
=> Update travis job

pkg/core/redis/pool.go
refs #1206 
In azure cluster, it often happens that server failed to connect to sentinels due to timeout.
=> Increase sentinel dial connection time out

pkg/gateway/middleware/app.go, pkg/gateway/middleware/app_test.go, pkg/gateway/model/app.go
Originally we reserved path `/_{gear}` for gears.
This update change to route known path only, so only _auth and _asset will be routed to auth and asset gear corresponding.
For the other path that start with `/_`, we will check the deployment route.
We need this update for controller, so that we can add deployment route for controller.
=> Update resolve gear path prefix fallback to known gears only

cmd/auth/main.go, pkg/auth/dependency/webapp/post_no_cache_middleware.go, pkg/auth/dependency/webapp/template.go, static/authui/css/main.css
ref #1288
I cannot reproduce the original bug.
The first commit fixes a UX bug. Some links span the whole column but its text is very short. The user may mistakenly click on the blank area.
The second commit ensures POST request are not cache-able. Some POST requests contain login ID and password which should not be cached at all.
=> Fix some Auth UI Web App bugs

pkg/auth/handler/sso/unlink.go, pkg/auth/handler/sso/unlink_test.go
Reason is public API and we use the term Identity in public API.
fix #1316
=> Rename OAuthPrincipalNotFound to OAuthIdentityNotFound

cmd/auth/main.go, pkg/auth/dependency/authn/provider.go, pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/csrf.go, pkg/auth/dependency/webapp/csrf_middleware.go, pkg/auth/dependency/webapp/redirect.go, pkg/auth/dependency/webapp/redirect_test.go, pkg/auth/dependency/webapp/sso_state.go, pkg/auth/dependency/webapp/validate_provider_impl.go, pkg/auth/handler/webapp/login.go, pkg/auth/handler/webapp/sso_callback.go, pkg/auth/handler/webapp/wire.go, pkg/auth/handler/webapp/wire_gen.go
require #1331 
connect #1320 
The pr only covers login with general sso login, tested with google login only.
Question:
- Now when there is error in the sso flow, we redirect user back to login page. Maybe we should update the error display to a more generic place? Currently it shows above the login id form
TODO:
- Login with apple flow should be different? Will further study.
- Link with sso provider, the connect buttons should be appear in the settings page
=> Auth UI SSO login part 1

migrations/auth/1588670460_add_login_id_unique_key_constraint.down.sql, migrations/auth/1588670460_add_login_id_unique_key_constraint.up.sql
We had unique index to app_id, realm and unique_key columns, the index was dropped when we deleted realm column. Add back the unique index to app_id and unique_key.
=> Add back unique constraint to login id identity table

pkg/auth/dependency/webapp/csrf_middleware.go, pkg/core/samesite/incompatible.go, pkg/core/samesite/incompatible_test.go
refs #1368 
Tested login in Mac Chrome 60
=> Handle `SameSite=None` is unsupported by some old browsers

pkg/core/http/cookie.go, pkg/core/http/cookie_test.go
=> Handle IPv4 and IPv6 in CookieDomainFromETLDPlusOneWithoutPort

pkg/auth/dependency/identity/claim_key.go, pkg/auth/dependency/identity/info.go, pkg/auth/dependency/identity/provider/conversion.go, pkg/auth/dependency/identity/provider/provider.go, pkg/auth/dependency/interaction/flows/auth_api_sso.go, pkg/auth/dependency/interaction/flows/user_ctrl.go, pkg/auth/dependency/interaction/flows/webapp_sso.go, pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/dependency/interaction/provider_commit_test.go, pkg/auth/dependency/interaction/provider_flow_test.go, pkg/auth/dependency/interaction/user.go, pkg/auth/handler/list_identities.go, pkg/auth/handler/list_identities_test.go, pkg/auth/model/identity.go
=> Redefine some OAuth claim keys

cmd/auth/main.go
fix #1459
Actually a static validator instance for each endpoint is better than a global validator that we have to register schema in main.go. But let's address that in another issue.
=> Register challenge schema

static/authui/js/main.js
By observation, Safari has back-forward cache while Chrome does not.
fix #1483
=> Be compatible with back-forward cache
