SkygearIO/skygear-server

handler/record.go, skydb/pq/builder.go, skydb/pq/builder_test.go, skydb/record.go, skydb/skyconv/map.go
connect oursky/skygear-server#647
=> Support public read access ACL

main.go
connect oursky/skygear-server#624
=> Add version number to getsentry event

examples/quickstart/fabfile.py, scripts/quickstart/README.md, scripts/quickstart/cloudformation-rds.template, scripts/quickstart/cloudformation.template, scripts/quickstart/files/motd, scripts/quickstart/myapp/docker-compose.yml, scripts/quickstart/myapp/nginx-default.conf, scripts/quickstart/myapp/static/html/index.html, scripts/quickstart/scripts/cleanup.sh, scripts/quickstart/scripts/set_version.sh, scripts/quickstart/template.json
=> Update quickstart example

main.go, router/logging.go
=> Use mime package for mime processing and allow config of mime type concern

router/model.go, router/router_test.go
=> Fix missing headers returned from plugins

skydb/pq/recorddb.go, skydb/pq/schema.go, skydb/record.go
=> Check sequence exist before update

handler/record.go, preprocessor/auth.go, preprocessor/dev.go, router/model.go
=> Allow master key to override ACL restriction

README.md
=> Update the doc link to http://docs.skygear.io/

handler/auth_test.go, skydb/pq/migration/c0397f15027_citext_on_auth.go, skydb/pq/migration/full.go, skydb/pq/migration/revision_list.go, skydb/pq/user_test.go, skydb/skydbtest/skydbtest.go
=> Case insensitive auth action, signup/login on username and email

handler/record.go, handler/record_test.go, skydb/pq/builder.go, skydb/pq/builder_test.go, skydb/pq/recorddb.go, skydb/query.go
This fixes the problem when no database is specified or when there
is no current user.
connects #58
connects #59
=> Fix ACL in query

handler/record.go, handler/record_test.go, skydb/pq/builder.go, skydb/pq/builder_test.go, skydb/pq/recorddb.go, skydb/pq/recorddb_test.go, skydb/query.go
=> Bypass access control with master key

authtoken/authtoken-redis.go, authtoken/authtoken.go, authtoken/authtoken_test.go
=> Change the token expiry default to never

authtoken/authtoken-fs.go, authtoken/authtoken-redis.go, authtoken/authtoken.go, authtoken/authtoken_test.go, authtoken/authtokentest/authtokentest.go, handler/auth.go, handler/auth_test.go, main.go, skyconfig/config.go, skyconfig/config_test.go
=> Config auth token expiry time and default

handler/user.go, handler/user_test.go
=> Include user role in user query

Godeps/Godeps.json, authtoken/authtoken-fs.go, authtoken/authtoken-redis.go, authtoken/authtoken.go, authtoken/authtokentest/authtokentest.go, authtoken/jwt.go, authtoken/jwt_test.go, authtoken/stateless.go, authtoken/stateless_test.go, handler/auth.go, handler/auth_test.go, main.go, preprocessor/auth.go, preprocessor/preprocessor.go, preprocessor/preprocessor_test.go, router/gateway_test.go, router/model.go, skyconfig/config.go, skydb/pq/conn.go, skydb/pq/migration/88a550bf579_add_token_not_before_to_user.go, skydb/pq/migration/full.go, skydb/pq/user.go, skydb/pq/user_test.go, skydb/userinfo.go, skydb/userinfo_test.go
=> Add Stateless token store

handler/asset.go, handler/auth.go, handler/query.go, handler/record.go, handler/role.go, handler/user.go, plugin/handler.go, plugin/hook.go, plugin/lambda.go, router/errors.go, router/router_test.go, skydb/pq/builder.go, skydb/pq/builder_test.go, skydb/pq/recorddb_test.go, skydb/query.go, skyerr/errorcode_string.go, skyerr/skyerr.go
connects skygeario/skygear-server#56
=> Check field exists before performing query

postgresql.md, skydb/pq/migration/48b961caa.go, skydb/pq/migration/c0397f15027_citext_on_auth.go, skydb/pq/migration/full.go
I modify the migration directly, since current deployment is one schema per
db. I think it will be okay for just make it works better in new deployment.
connect #53
=> Create the citext to public schema

pubsub/ws.go
connect SkygearIO/skygear-SDK-JS#27
=> Handle invalid data format for pubsub actions

handler/query.go, handler/query_test.go, handler/user.go, handler/user_test.go, skydb/conn.go, skydb/mock_skydb/mock.go, skydb/pq/builder.go, skydb/pq/builder_test.go, skydb/pq/pq_test.go, skydb/pq/recorddb_test.go, skydb/pq/user.go, skydb/pq/user_test.go, skydb/query.go, skydb/query_test.go, skydb/skydbtest/skydbtest.go
connects skygeario/skygear-server#90
=> Support user discovery with username

handler/auth.go, handler/auth_test.go, skydb/conn.go, skydb/mock_skydb/mock.go, skydb/pq/role.go, skydb/pq/role_test.go, skydb/skydbtest/skydbtest.go
=> Assign default user role to new signup user

skydb/pq/migration/30d0a626888_add_username.go, skydb/pq/migration/41af1c8d394_add_user_role.go, skydb/pq/migration/551bc42a839_add_role_type.go, skydb/pq/migration/88a550bf579_add_token_not_before_to_user.go, skydb/pq/migration/bce7089fca4_add_default_admin.go, skydb/pq/migration/full.go, skydb/pq/migration/revision_list.go, skydb/pq/user_test.go
=> Add migration for initial admin user

handler/recordutil.go, main.go, preprocessor/conn.go, skydb/pq/conn.go, skydb/pq/pq.go, skydb/pq/schema.go, skydb/pq/schema_test.go, skydb/record.go, skydb/record_test.go
Requests authenticated with master key can temporarily override
this restriction.
connects #93
=> Disable schema migration for non-dev-mode

handler/device.go, handler/device_test.go, skydb/pq/device.go
=> Remove device with the same token when register

Godeps/Godeps.json, uuid/uuid.go
=> Update deps github.com/twinj/uuid

main.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/me.go, pkg/server/handler/me_test.go
=> Implement `me` endpoint to get current user

.env.example, glide.lock, glide.yaml, main.go, pkg/server/asset/asset.go, pkg/server/asset/cloud.go, pkg/server/asset/cloud_signer.go, pkg/server/asset/cloud_test.go, pkg/server/asset/fs.go, pkg/server/asset/s3.go, pkg/server/handler/asset.go, pkg/server/handler/asset_test.go, pkg/server/handler/file.go, pkg/server/handler/file_test.go, pkg/server/handler/record_test.go, pkg/server/skyconfig/config.go
=> Support Cloud Asset

pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/common.go, pkg/server/handler/me.go, pkg/server/handler/me_test.go, pkg/server/skydb/pq/migration/db76e79e987_add_last_login.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/pq/user.go, pkg/server/skydb/userinfo.go
=> Provide user last logged in and last seen at _user

pkg/server/handler/me.go, pkg/server/handler/me_test.go, pkg/server/skydb/pq/user.go, pkg/server/skydb/pq/user_test.go
It is due to the user query from DB don't have last login at. Updating
user will clear the value.
connects #110
=> Fix bugs on `me` clear out the last login at for user

pkg/server/authtoken/jwt.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/skydb/userinfo.go
=> Fix auth:password response invalid access token

scripts/docker-images/deps/Dockerfile
=> Add ca-certificate to deps building pipeline

Makefile, README.md, docker-compose.dev.yml
=> Allow run test with docker-compose

.gogocyclo, .travis.yml, Makefile, pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/broker_test.go, pkg/server/plugin/zmq/rpc.go, pkg/server/skydb/pq/pq_test.go
This will resolve socket exhaust problem on high concurrency.
connects #160
=> Use channel in messaging between goroutine instead of zmq.REQ

pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/broker_test.go
=> Make the broker stoppable and use new worker in each test case

main.go, pkg/server/skyconfig/config.go
=> Fix unable to configure sentry log hook

pkg/server/plugin/exec/process.go, pkg/server/plugin/exec/process_test.go, pkg/server/plugin/http/http.go, pkg/server/plugin/zmq/rpc.go
=> More log when plugin response is invalid

main.go, pkg/server/handler/device.go, pkg/server/handler/device_test.go, pkg/server/skydb/pq/device.go, pkg/server/skydb/pq/device_test.go
=> Support unregister device

glide.lock, glide.yaml, main.go, pkg/server/handler/device.go, pkg/server/handler/device_test.go, pkg/server/handler/push.go, pkg/server/handler/push_test.go, pkg/server/push/apns.go, pkg/server/push/apns_test.go, pkg/server/push/cert_apns.go, pkg/server/push/cert_apns_test.go, pkg/server/push/token_apns.go, pkg/server/push/token_apns_test.go, pkg/server/skyconfig/config.go, pkg/server/skydb/conn.go, pkg/server/skydb/device.go, pkg/server/skydb/mock_skydb/mock.go, pkg/server/skydb/pq/device.go, pkg/server/skydb/pq/device_test.go, pkg/server/skydb/pq/migration/1981535c8aeb_add_device_topic.go, pkg/server/skydb/pq/migration/full.go
=> Support token based APNS

README.md, default.nix
Now you can build with a single command `nix-build`~~
=> Add Nix derivation for building

linux-setup.md
=> Commands for setting up skygear in Linux env

pkg/server/plugin/zmq/broker.go
=> Improve the plugin transport logging for bytes

pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/rpc.go
=> Make parcel generate payload

Makefile, pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/broker_test.go, pkg/server/plugin/zmq/rpc.go
connect #303
It is based on #316 since it also test parcel creation. The coverage is now 64.4%
=> Add test cases

pkg/server/plugin/zmq/broker.go, pkg/server/plugin/zmq/broker_test.go
connect https://github.com/SkygearIO/skygear-server/issues/304
=> Allow plugin to send request to server

pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go
=> Create user when master key is provided

pkg/server/handler/record_test.go, pkg/server/handler/recordutil.go, pkg/server/skydb/skydbtest/skydbtest.go
connect #327 
This PR makes sure asset's information is complete, but [it is not perfect](https://github.com/SkygearIO/skygear-server/issues/327#issuecomment-288522101)
=> Return asset content type in response of record save

main.go, pkg/server/preprocessor/preprocessor.go
connect https://github.com/SkygearIO/skygear-SDK-Android/issues/89
=> Make RequireUser preprocessor gives a better error message

pkg/server/plugin/zmq/rpc.go
connect https://github.com/SkygearIO/skygear-server/issues/347
=> Remove response channel when it is not consumed anymore

pkg/server/skydb/access.go, pkg/server/skydb/access_test.go, pkg/server/skydb/pq/access_schema.go, pkg/server/skydb/pq/access_schema_test.go
=> Fix FieldACL checking order

pkg/server/handler/auth_test.go, pkg/server/handler/record.go, pkg/server/handler/record_test.go, pkg/server/handler/recordutil.go, pkg/server/router/errors.go, pkg/server/skydb/access.go, pkg/server/skydb/access_test.go, pkg/server/skydb/pq/access_schema.go, pkg/server/skydb/pq/conn.go, pkg/server/skydb/record.go, pkg/server/skydb/skydbtest/skydbtest.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
connects #376
refs skygeario/features#48
=>  Implement read/write Field ACL for fixed user roles

pkg/server/skydb/access.go, pkg/server/skydb/access_test.go
connects #379
connects #378
refs SkygearIO/features#48
=> Support Field ACL for dynamic field and owner

main.go, pkg/server/handler/handlertest/gomock.go, pkg/server/handler/schema.go, pkg/server/handler/schema_test.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/skydb/access.go, pkg/server/skydb/skyconv/map.go
refs #375
refs SkygearIO/features#48
=> Implement field ACL get/update handlers

pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/record.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/recordutil/recordutil.go, pkg/server/skydb/skydbtest/skydbmockutil.go
=> Signup with user profile

pkg/server/asset/fs.go, pkg/server/asset/fs_test.go
Properly close the base64Encoder
connects #427
=> Fix the false positive of hmac.equal check

main.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/common.go, pkg/server/handler/device.go, pkg/server/handler/me.go, pkg/server/handler/record.go, pkg/server/handler/subscription.go, pkg/server/plugin/handler.go, pkg/server/plugin/lambda.go, pkg/server/preprocessor/preprocessor.go
=> Include user profile in change password response

.travis.yml, README.md, glide.lock, glide.yaml, scripts/docker-images/deps/Dockerfile, scripts/docker-images/godev/Dockerfile
=> Update goczmq to v4

pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/common.go, pkg/server/handler/device_test.go, pkg/server/handler/file_test.go, pkg/server/handler/me_test.go, pkg/server/handler/record_test.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/recordutil/recordutil.go, pkg/server/skydb/authinfo.go, pkg/server/skydb/pq/migration/81beb4d8658c_add_last_login_at_acl.go, pkg/server/skydb/pq/migration/83f549ff247b_move_last_login_at.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/pq/user.go, pkg/server/skydb/pq/user_test.go, pkg/server/skydb/record.go, pkg/server/skydb/skydbtest/skydbtest.go
=> Move last login time to user record

pkg/server/recordutil/recordutil.go
=> Mention the return record is copy of the original in RecordResultFilter

pkg/server/skydb/pq/migration/f0c53134d25d_rename_table_user_to_auth.go
=> Add missing user record in _user to _auth migration

pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/skydb/pq/recorddb.go, pkg/server/skydb/skydbtest/skydbmockutil.go
=> Handle unique constraint violation error when signup

pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/user_test.go
=> Remove add admin account and admin role logic in migration seed data

pkg/server/handler/record_test.go, pkg/server/recordutil/recordutil.go, pkg/server/skydb/pq/access_schema_test.go, pkg/server/skydb/pq/migration/b55e91bc9391_add_auth_data_field_access.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go
=> Set default field discoverability to user auth record keys

main.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/skydb/authinfo.go
connect #459 
- Remove login logic from link provider handler 
- Add unlink provider handler
=> SSO link and unlink handler

glide.lock, glide.yaml, pkg/server/asset/s3.go, pkg/server/asset/s3_test.go
=> Update to use official aws-sdk-go

README.md
(I know we don't have skygear-sso open source yet, just add there so when we does it will be a correct link)
=> Add links to README.md, and change Google Forum to discuss.skygear.io

.env.example
=> update .env.example to have all vars and add more comments

pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/record.go, pkg/server/handler/record_test.go, pkg/server/plugin/transportstate_string.go, pkg/server/recordutil/recordutil.go, pkg/server/router/accesskeytype_string.go, pkg/server/skydb/accessmodel_string.go, pkg/server/skydb/database.go, pkg/server/skydb/datatype_string.go, pkg/server/skydb/mock_database_test.go, pkg/server/skydb/mock_skydb/mock_database.go, pkg/server/skydb/mock_skydb/mock_tx_database.go, pkg/server/skydb/operator_string.go, pkg/server/skydb/pq/recorddb.go, pkg/server/skydb/pq/recorddb_test.go, pkg/server/skydb/query.go, pkg/server/skydb/skydbtest/skydbtest.go, pkg/server/skyerr/errorcode_string.go
=> Record acl for transient fields

.env.example, .gogocyclo, Gopkg.lock, Gopkg.toml, docker-compose.yml, main.go, pkg/server/handler/authutil.go, pkg/server/handler/sso_customtoken.go, pkg/server/handler/sso_customtoken_test.go, pkg/server/router/errors.go, pkg/server/skyconfig/config.go, pkg/server/skydb/conn.go, pkg/server/skydb/customtoken.go, pkg/server/skydb/mock_conn_test.go, pkg/server/skydb/mock_skydb/mock_conn.go, pkg/server/skydb/pq/customtoken.go, pkg/server/skydb/pq/customtoken_test.go, pkg/server/skydb/pq/migration/6250fd676f58_add_sso_custom_token.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/skydbtest/skydbtest.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
No test case for the handler at the moment
connects #494
=> Add new sso:custom_token:login handler

pkg/server/preprocessor/preprocessor_test.go, pkg/server/skydb/skydb.go, pkg/server/skydb/skydb_test.go
Provide a public Mock method intended to use in testing
Also add test case for the Mock method and restore
=> Fix test failure after refactoring

.gogocyclo, main.go, pkg/server/audit/trail.go, pkg/server/handler/auth.go, pkg/server/handler/auth_disable_set.go, pkg/server/handler/auth_disable_set_test.go, pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/sso.go, pkg/server/handler/sso_customtoken.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/router/errors.go, pkg/server/skydb/authinfo.go, pkg/server/skydb/authinfo_test.go, pkg/server/skydb/pq/migration/b3163d49bd6d_add_disabled_fields.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/pq/user.go, pkg/server/skydb/pq/user_test.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
=> Support enable/disable user account

.env.example, main.go, pkg/server/audit/trail.go, pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/common.go, pkg/server/handler/me.go, pkg/server/handler/me_test.go, pkg/server/handler/sso_customtoken_test.go, pkg/server/handler/sso_test.go, pkg/server/handler/user_verify_set.go, pkg/server/handler/user_verify_set_test.go, pkg/server/plugin/transport.go, pkg/server/plugin/transport_test.go, pkg/server/preprocessor/preprocessor.go, pkg/server/preprocessor/preprocessor_test.go, pkg/server/router/errors.go, pkg/server/router/model.go, pkg/server/skyconfig/config.go, pkg/server/skydb/authinfo.go, pkg/server/skydb/pq/migration/df95984b298d_add_verified_fields.go, pkg/server/skydb/pq/migration/full.go, pkg/server/skydb/pq/migration/revision_list.go, pkg/server/skydb/pq/user.go, pkg/server/skydb/pq/user_test.go, pkg/server/skyerr/errorcode_string.go, pkg/server/skyerr/skyerr.go
connects #540
connects #539
connects #538
connects #537
=> Support handle user verified status

pkg/server/handler/record_test.go, pkg/server/recordutil/recordutil.go
=> Inject assets signer before calling before_save hook

pkg/server/asset/asset.go, pkg/server/asset/cloud.go, pkg/server/asset/cloud_test.go, pkg/server/asset/fs.go, pkg/server/asset/s3.go, pkg/server/handler/asset.go, pkg/server/handler/asset_test.go, pkg/server/handler/file_test.go, pkg/server/handler/record_test.go
=> Fix content-type not sent to assetd

pkg/server/handler/auth.go, pkg/server/handler/auth_test.go, pkg/server/handler/authutil.go, pkg/server/handler/common.go, pkg/server/handler/me.go, pkg/server/handler/sso.go, pkg/server/handler/sso_customtoken.go, pkg/server/recordutil/recordutil.go
=> Fix unable to login with user profile that has asset

pkg/server/handler/auth_test.go, pkg/server/handler/me_test.go, pkg/server/handler/record.go, pkg/server/handler/record_test.go, pkg/server/handler/relation_test.go, pkg/server/handler/sso_customtoken_test.go, pkg/server/handler/sso_test.go, pkg/server/plugin/exec/process_test.go, pkg/server/plugin/http/http_test.go, pkg/server/plugin/lambda_test.go, pkg/server/skydb/record.go, pkg/server/skydb/skyconv/map.go, pkg/server/skydb/skyconv/record.go
=> Add record type and ID to request and response payload

pkg/server/handler/auth_test.go, pkg/server/handler/me_test.go, pkg/server/handler/record.go, pkg/server/handler/record_test.go, pkg/server/handler/relation_test.go, pkg/server/handler/sso_customtoken_test.go, pkg/server/handler/sso_test.go, pkg/server/plugin/exec/process_test.go, pkg/server/plugin/http/http_test.go, pkg/server/plugin/lambda_test.go, pkg/server/skydb/record.go, pkg/server/skydb/skyconv/map.go, pkg/server/skydb/skyconv/record.go
=> Update record:delete action for record ID

.gitignore, Gopkg.lock, docker-compose.yml, pkg/server/asset/asset.go, pkg/server/asset/error.go, pkg/server/asset/fs.go, pkg/server/asset/s3.go, pkg/server/handler/file.go
=> Support byte-range when serving asset file

pkg/server/asset/cloud.go, pkg/server/asset/cloud_test.go
connect oursky/skygear-cloud#533
=> Fix cloud asset filename encoding issue

pkg/auth/handler/login.go, pkg/core/handler/context.go, pkg/core/handler/factory.go, pkg/core/server/server.go
Handler is not tenant aware
connect #630
=> Move tenant code to HandlerFactory

cmd/auth/main.go, cmd/gateway/main.go, pkg/core/auth/authn/authn.go, pkg/core/auth/authz/policy.go, pkg/core/auth/info.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/middleware/tenant.go, pkg/core/model/app.go, pkg/core/server/server.go, pkg/gateway/middleware/tenant.go, pkg/gateway/provider/config.go
- moved some functions from gateway to core
- fixed some constant key string
=> next: Read api key and config in middleware with dev mode

README.md, cmd/gateway/main.go, pkg/core/config/tenant.go, pkg/core/logging/logging.go, pkg/gateway/db/pq/app.go, pkg/gateway/db/pq/pq.go, pkg/gateway/db/pq/store.go, pkg/gateway/db/pq/store_exec.go, pkg/gateway/db/pq/types.go, pkg/gateway/db/store.go, pkg/gateway/middleware/tenant.go, pkg/gateway/model/app.go, pkg/gateway/model/plan.go, pkg/gateway/provider/config.go
connect #624
connect #625 
connect #626 
WIP: Gateway startup config #656
FYI: My testing sql for dev
https://gist.github.com/carmenlau/febf77b577c5f2ee4665b29ed76b8348
=> next: gateway load app from db

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
Example config json in db
```
{
"DATABASE_URL": "postgres://postgres:@localhost/postgres?sslmode=disable",
"API_KEY": "api_key",
"MASTER_KEY": "master_key",
"TOKEN_STORE": {
"SECRET": "secret",
"EXPIRY": 0
},
"APP_NAME": "next"
}
```
=> Update tenant config serialisation format

pkg/server/skydb/pq/builder/factory.go, pkg/server/skydb/pq/builder/predicate_test.go, pkg/server/skydb/pq/builder/sort.go, pkg/server/skydb/pq/recorddb.go, pkg/server/skydb/pq/recorddb_test.go
=> Support sort by key path

cmd/auth/main.go, pkg/auth/handler/disable.go, pkg/core/auth/authinfo/pq/store.go
=> next: Add set disable handler

cmd/migrate/core/1538535465_add_user_last_login_at.down.sql, cmd/migrate/core/1538535465_add_user_last_login_at.up.sql, pkg/auth/handler/signup.go, pkg/core/auth/authinfo/authinfo.go, pkg/core/auth/authinfo/pq/store.go
=> next: Signup last login at

pkg/auth/dependency/userprofile.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/inject/inject.go
=> next: Auth user profile config

cmd/auth/main.go, pkg/auth/handler/logout.go
=> next: Logout handler 

pkg/auth/dependency/provider/password/password.go, pkg/auth/dependency/provider/password/principal.go, pkg/auth/dependency/userprofile.go, pkg/auth/handler/handler.go, pkg/auth/handler/login.go
=> next: Login handler

Makefile, pkg/core/auth/authinfo/authinfo_test.go, pkg/core/auth/authtoken/jwt.go, pkg/core/auth/authtoken/token.go, pkg/core/auth/authz/policy/accesskey_test.go, pkg/core/auth/authz/policy/authinfo.go, pkg/core/auth/authz/policy/authinfo_test.go, pkg/core/auth/authz/policy/compound_test.go, pkg/core/auth/authz/policy/disable_test.go, pkg/core/auth/authz/policy/role.go, pkg/core/auth/authz/policy/role_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/inject/inject_test.go, pkg/core/middleware/tenant_test.go
connect #686 
test added:
- core/inject
- core/middleware
- core/auth/authinfo
- core/auth/authz/policy
=> next: test case for core library

cmd/auth/main.go, cmd/migrate/core/1538621793_add_user_role.down.sql, cmd/migrate/core/1538621793_add_user_role.up.sql, pkg/auth/handler/role_assign.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/core/auth/authinfo/pq/store.go, pkg/core/auth/authinfo/pq/user_role.go, pkg/core/auth/authinfo/store.go, pkg/core/auth/authn/resolver/default.go, pkg/core/auth/authz/policy/role.go, pkg/core/auth/default.go, pkg/core/auth/role/pq/store.go, pkg/core/auth/role/store.go, pkg/core/handler/context/context.go
=> next: Role assign handler

pkg/auth/handler/disable.go, pkg/auth/handler/login.go, pkg/auth/handler/logout.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/core/audit/trail.go, pkg/core/audit/trail_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
=> next: Audit trail

cmd/auth/main.go, pkg/auth/dependency/provider/password/password.go, pkg/auth/handler/login.go, pkg/auth/handler/reset_password.go
=> next: reset password handler

pkg/auth/handler/disable.go, pkg/auth/handler/login.go, pkg/auth/handler/logout.go, pkg/auth/handler/me.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/role_assign.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/core/auth/default.go, pkg/core/db/context.go, pkg/core/db/sql_executor.go, pkg/core/handler/api.go, pkg/core/server/server.go
connect #682
I have made some big changes to the interface, since handler.Handler is removed and http.Handler is used instead. The AuthContext would need dependency to provide interface for access
=> next: DB transaction

pkg/auth/handler/me.go
=> next: me handler

.gometalinter.json, .travis.yml, Makefile, pkg/auth/handler/handler.go, pkg/auth/handler/login.go, pkg/auth/response/response.go, pkg/core/audit/trail.go, pkg/core/auth/authtoken/token.go, pkg/core/logging/logging.go, pkg/core/logging/text_formatter.go, pkg/gateway/db/pq/app.go, pkg/gateway/db/pq/store_exec.go, pkg/gateway/db/pq/types.go, pkg/gateway/model/plan.go, pkg/gateway/provider/config.go, pkg/server/handler/me.go
We separate the running at v1 and next. Next will have strict rule in the first
day.
=> Update the lint rule and code that apply to next

cmd/auth/main.go, pkg/auth/handler/role_revoke.go, pkg/auth/handler/role_revoke_test.go, pkg/core/auth/authinfo/mock_store.go, pkg/core/auth/authinfo/pq/user_role.go, pkg/core/auth/authinfo/store.go
=> next: revoke roles

pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/logging/logging.go, pkg/core/logging/mask_formatter.go
supports:
1. master key, API key
2. JWT access token
connects #220
=> next: sanitize log

cmd/auth/main.go, cmd/record/main.go, pkg/record/handler/save.go, pkg/record/inject.go
=> next: record gear setup

pkg/auth/dependency/provider/anonymous/anonymous.go, pkg/auth/dependency/provider/anonymous/mock_anonymous.go, pkg/auth/dependency/provider/anonymous/principal.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/inject.go
=> next: sign up anonymously

cmd/auth/main.go, pkg/auth/handler/role_default.go, pkg/auth/handler/role_default_test.go, pkg/core/auth/role/mock_store.go, pkg/core/auth/role/pq/store.go, pkg/core/auth/role/store.go
=> next: Role default handler

pkg/auth/dependency/provider/anonymous/tx_provider.go, pkg/auth/dependency/provider/password/tx_provider.go
=> safeXXXStore should invoke impl implementation

cmd/record/main.go, pkg/core/auth/mock_context.go, pkg/record/dependency/record/mock_store.go, pkg/record/dependency/record/pq/builder/factory.go, pkg/record/dependency/record/pq/recorddb.go, pkg/record/dependency/record/pq/tx_store.go, pkg/record/dependency/record/rows.go, pkg/record/dependency/record/store.go, pkg/record/handler/fetch.go, pkg/record/handler/parser.go, pkg/record/handler/query.go, pkg/record/handler/query_test.go, pkg/record/handler/save.go, pkg/record/handler/utils.go
=> next: record query handler

cmd/record/main.go, pkg/record/handler/schema_delete.go, pkg/record/handler/schema_delete_test.go
=> next: schema delete handler

cmd/record/main.go, pkg/record/handler/schema_rename.go, pkg/record/handler/schema_rename_test.go
=> next: schema rename handler

cmd/record/main.go, pkg/record/handler/schema_fetch.go, pkg/record/handler/schema_fetch_test.go
=> next: schema fetch handler

cmd/record/main.go, pkg/record/handler/creation_access.go, pkg/record/handler/creation_access_test.go
=> next: creation access handler

cmd/record/main.go, pkg/record/dependency/record/mock_store.go, pkg/record/handler/field_access_get.go, pkg/record/handler/field_access_get_test.go, pkg/record/handler/field_access_update.go, pkg/record/handler/field_access_update_test.go, pkg/record/handler/field_access_utils.go
=> next: field acl get and update handler

pkg/record/dependency/recordconv/map.go, pkg/record/dependency/recordconv/record.go, pkg/record/handler/delete.go, pkg/record/handler/delete_test.go, pkg/record/handler/fetch.go, pkg/record/handler/fetch_test.go, pkg/record/handler/query_test.go, pkg/record/handler/save.go, pkg/record/handler/save_test.go, pkg/record/handler/utils.go
=> next: remove old format record id

pkg/auth/dependency/userprofile/mock_store.go, pkg/auth/dependency/userprofile/recordstore.go, pkg/auth/dependency/userprofile/tx_provider.go, pkg/auth/dependency/userprofile/userprofile.go, pkg/auth/handler/login.go, pkg/auth/handler/me.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/record/handler/save.go
=> Use record gear to save profile

README.md, cmd/gateway/.env.example, cmd/gateway/main.go, cmd/migrate/revisions/gateway/1542181806_update_support_multiple_gear_versions.down.sql, cmd/migrate/revisions/gateway/1542181806_update_support_multiple_gear_versions.up.sql, pkg/gateway/config/config.go, pkg/gateway/db/pq/app.go, pkg/gateway/middleware/tenant.go, pkg/gateway/model/app.go, pkg/gateway/model/plan.go
=> next: Next gateway multiple gear versions

Gopkg.lock, Gopkg.toml, examples/welcome_email.txt, pkg/auth/dependency/userprofile/userprofile.go, pkg/auth/dependency/welcemail/sender.go, pkg/auth/dependency/welcemail/template.go, pkg/auth/dependency/welcemail/testsender.go, pkg/auth/inject.go
=> next: Welcome email handler with email template

pkg/auth/dependency/welcemail/mock_sender.go, pkg/auth/dependency/welcemail/task.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/inject.go
=> next: Add test for welcome email 

pkg/auth/dependency/password_checker.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/reset_password_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/inject.go, pkg/core/audit/password_checker.go, pkg/core/audit/password_checker_test.go, pkg/core/audit/pw_house_keeper.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/skyerr/status_code.go
=> next: Apply password policy config

cmd/auth/main.go, cmd/migrate/revisions/auth/1543327214_add_verify_code.down.sql, cmd/migrate/revisions/auth/1543327214_add_verify_code.up.sql, examples/verify_email.txt, examples/verify_error.html, examples/verify_sms.txt, examples/verify_success.html, pkg/auth/dependency/userverify/code.go, pkg/auth/dependency/userverify/sender.go, pkg/auth/dependency/userverify/verifycode/store.go, pkg/auth/dependency/userverify/verifycode/verifycode.go, pkg/auth/handler/verify_request.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
SMS verification would be in another PR(s).
connect #780
=> next: User verify request with email

cmd/auth/main.go, pkg/auth/dependency/sso/iframe_html.go, pkg/auth/handler/ssohandler/config.go, pkg/auth/handler/ssohandler/iframe_handler.go, pkg/auth/handler/ssohandler/iframe_handler_test.go, pkg/auth/inject.go, pkg/core/config/tenant.go
=> next: sso iframe handler

Gopkg.lock, Gopkg.toml, pkg/auth/dependency/userverify/sender.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/sms/client.go, pkg/core/sms/nexmo.go, pkg/core/sms/twilio.go
=> next: User verify request with sms

cmd/auth/main.go, cmd/migrate/revisions/auth/1542793176_drop_auth_principal_constraint.down.sql, cmd/migrate/revisions/auth/1542793176_drop_auth_principal_constraint.up.sql, cmd/migrate/revisions/auth/1543462881_add_custom_token.down.sql, cmd/migrate/revisions/auth/1543462881_add_custom_token.up.sql, pkg/auth/dependency/provider/customtoken/claims.go, pkg/auth/dependency/provider/customtoken/customtoken.go, pkg/auth/dependency/provider/customtoken/mock_provider.go, pkg/auth/dependency/provider/customtoken/principal.go, pkg/auth/dependency/provider/customtoken/provider.go, pkg/auth/dependency/provider/customtoken/tx_provider.go, pkg/auth/handler/ssohandler/customtoken.go, pkg/auth/handler/ssohandler/customtoken_test.go, pkg/auth/handler/ssohandler/handler.go, pkg/auth/inject.go, pkg/core/auth/authtoken/mock_store.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
connect #776 
TODO:
- ~~Create and update user profile~~ ( Done in #822)
- Sending welcome email
- ~~Audit trail~~
=> next: login with custom token

pkg/auth/dependency/userprofile/mock_store.go, pkg/auth/dependency/userprofile/recordstore.go, pkg/auth/dependency/userprofile/store.go, pkg/auth/dependency/userprofile/tx_provider.go, pkg/auth/dependency/userprofile/userprofile.go, pkg/auth/handler/ssohandler/customtoken.go, pkg/auth/handler/ssohandler/customtoken_test.go
=> next: Upsert user profile when login with custom token

cmd/auth/main.go, pkg/auth/handler/forgot_password_reset.go, pkg/auth/handler/forgot_password_reset_test.go, pkg/auth/inject.go
=> next: Forgot password reset password handler

cmd/auth/main.go, pkg/auth/handler/change_password.go, pkg/auth/handler/change_password_test.go, pkg/auth/handler/reset_password.go, pkg/core/auth/authinfo/mock_store.go
=> next: change password handler

pkg/auth/dependency/provider/password/authdata.go, pkg/auth/dependency/provider/password/authdata_test.go, pkg/auth/dependency/provider/password/mock_password.go, pkg/auth/dependency/provider/password/password.go, pkg/auth/dependency/provider/password/provider.go, pkg/auth/dependency/provider/password/tx_provider.go, pkg/auth/handler/login.go, pkg/auth/handler/login_test.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
=> next: Fix auth record keys

cmd/auth/main.go, pkg/auth/dependency/audit/pw_house_keeper.go, pkg/auth/handler/change_password.go, pkg/auth/handler/change_password_test.go, pkg/auth/handler/forgotpwd/reset.go, pkg/auth/handler/forgotpwd/reset_form.go, pkg/auth/handler/forgotpwd/reset_test.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/reset_password_test.go, pkg/auth/handler/signup.go, pkg/auth/inject.go, pkg/auth/task/pw_house_keeper.go, pkg/core/async/mock_queue.go, pkg/core/async/queue.go
=> next: password housekeeper

examples/reset_password_error.html, examples/reset_password_success.html, pkg/auth/dependency/forgotpwdemail/resetpwd_html.go, pkg/auth/inject.go, pkg/auth/template/name.go, pkg/auth/template/reset_password_error_html.go, pkg/auth/template/reset_password_html.go, pkg/auth/template/reset_password_success_html.go, pkg/auth/template/template.go
=> next: Support default template for reset password htmls

cmd/auth/main.go, pkg/auth/dependency/provider/oauth/mock_oauth.go, pkg/auth/dependency/provider/oauth/oauth.go, pkg/auth/dependency/provider/oauth/provider.go, pkg/auth/dependency/provider/oauth/tx_provider.go, pkg/auth/handler/sso/provider_profiles.go, pkg/auth/handler/sso/provider_profiles_test.go
=> next: get oauth provider profiles handler

cmd/gateway/main.go, examples/reset_password.html, pkg/auth/dependency/forgotpwdemail/resetpwd_html.go, pkg/auth/dependency/forgotpwdemail/sender.go, pkg/auth/dependency/userverify/sender.go
=> next: Fix link in template

cmd/auth/main.go, pkg/auth/dependency/provider/oauth/mock_oauth.go, pkg/auth/dependency/provider/oauth/oauth.go, pkg/auth/dependency/provider/oauth/provider.go, pkg/auth/dependency/provider/oauth/tx_provider.go, pkg/auth/dependency/sso/authinfo.go, pkg/auth/dependency/sso/facebook.go, pkg/auth/dependency/sso/google.go, pkg/auth/dependency/sso/instagram.go, pkg/auth/dependency/sso/linkedin.go, pkg/auth/dependency/sso/mock_provider.go, pkg/auth/dependency/sso/sso.go, pkg/auth/handler/sso/auth_handler.go, pkg/auth/handler/sso/link.go, pkg/auth/handler/sso/link_test.go, pkg/auth/handler/sso/login.go, pkg/auth/handler/sso/login_test.go, pkg/auth/handler/sso/sso.go, pkg/auth/handler/sso/unlink.go, pkg/auth/handler/sso/unlink_test.go
connects #826
connects #789
connects #825
=> next: Support sso link, unlink, login handler

pkg/auth/dependency/userverify/sender.go, pkg/auth/dependency/userverify/verify_html.go, pkg/auth/handler/userverify/verify_code.go, pkg/auth/handler/userverify/verify_code_form.go, pkg/auth/handler/userverify/verify_utils.go, pkg/auth/inject.go, pkg/auth/template/name.go, pkg/auth/template/template.go, pkg/auth/template/verify_error_html.go, pkg/auth/template/verify_success_html.go, pkg/core/template/engine.go, pkg/core/template/engine_test.go
=> next: Verify code form handler

pkg/auth/handler/disable.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/role_admin.go, pkg/auth/handler/role_assign.go, pkg/auth/handler/role_default.go, pkg/auth/handler/role_get.go, pkg/auth/handler/role_get_test.go, pkg/auth/handler/role_revoke.go, pkg/auth/handler/sso/login.go, pkg/core/auth/authz/policy/compound.go, pkg/core/auth/authz/policy/compound_test.go, pkg/core/server/server.go
=> next: Revise handler authz

pkg/auth/dependency/sso/authinfo.go, pkg/auth/handler/sso/auth_handler.go, pkg/auth/handler/sso/auth_handler_test.go
- when callback url is missing, return 400 bad request
- in other cases, should send back error response to the client via redirect
connects #788
=> next: Refactor error handling in sso auth_handler

cmd/migrate/revisions/auth/1546592189_add_unique_constraint_to_auth_provider_oauth.down.sql, cmd/migrate/revisions/auth/1546592189_add_unique_constraint_to_auth_provider_oauth.up.sql, pkg/auth/handler/sso/sso.go
=> next: Should link user only when oauth principal can't be found

pkg/auth/dependency/sso/sso.go, pkg/auth/handler/sso/link.go, pkg/auth/handler/sso/link_test.go, pkg/auth/handler/sso/login.go, pkg/auth/handler/sso/login_test.go
Payload contains access token only, not the AccessTokenResp from provider.
connects #825
connects #826
=> Fix payload decode in login or link with access token

pkg/auth/dependency/provider/password/authdata.go, pkg/auth/dependency/provider/password/authdata_test.go, pkg/auth/dependency/provider/password/mock_password.go, pkg/auth/dependency/provider/password/password.go, pkg/auth/dependency/provider/password/provider.go, pkg/auth/dependency/provider/password/tx_provider.go, pkg/auth/dependency/sso/authinfo_processor.go, pkg/auth/dependency/sso/instagram.go, pkg/auth/dependency/sso/mock_provider.go, pkg/auth/dependency/sso/sso.go, pkg/auth/handler/login.go, pkg/auth/handler/login_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/link_test.go, pkg/auth/handler/sso/sso.go
=> next: Should validate zero value in authData

pkg/auth/dependency/userverify/senderfactory.go, pkg/auth/dependency/userverify/testsender.go, pkg/auth/handler/userverify/verify_request.go, pkg/auth/inject.go, pkg/auth/template/name.go, pkg/core/mail/dialer.go, pkg/core/template/engine.go
=> next: Verify request test handler

.travis.yml, Dockerfile, Dockerfile.make, Gopkg.lock, Gopkg.toml, pkg/server/skydb/pq/types.go, pkg/server/skydb/record.go
connect #886 
`paulmach/go.geo` is deprecated
=> Replace `paulmach/go.geo` with `paulmach/orb`

Dockerfile
=> Update docker based image to alpine:3.8

Dockerfile, cmd/auth/Dockerfile, cmd/gateway/Dockerfile, cmd/migrate/Dockerfile, cmd/record/Dockerfile
=> chore(dockerfile): updates to alpine 3.8

Dockerfile, Gopkg.lock, Gopkg.toml
=> Fix fail to start server docker image with plugin that use zmq transport

cmd/gateway/main.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/gateway/middleware/app.go, pkg/gateway/model/context.go
auth gear `PathPrefix` should put before cloud function
=> Fix gear routing match order and fix context nil exception

cmd/auth/main.go, pkg/core/server/option.go, pkg/core/server/server.go
So gear can has the same path in  both single and multi tenant mode.
=> Support setting gear path prefix

pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/customtoken.go, pkg/auth/handler/sso/sso.go
=> Update error response when createPrincipal failed

cmd/migrate/revisions/gateway/1552990000_add_cloud_code_backend.down.sql, cmd/migrate/revisions/gateway/1552990000_add_cloud_code_backend.up.sql, pkg/gateway/config/config.go, pkg/gateway/db/pq/cloudcode.go, pkg/gateway/handler/cloudcode.go, pkg/gateway/model/cloudcode.go
=> Support multiple cloud code backend

cmd/migrate/revisions/gateway/1553247010_add_default_plan.down.sql, cmd/migrate/revisions/gateway/1553247010_add_default_plan.up.sql, cmd/migrate/revisions/gateway/1553500733_add_domain_unique_constraint.down.sql, cmd/migrate/revisions/gateway/1553500733_add_domain_unique_constraint.up.sql, pkg/gateway/db/pq/app.go
connect skygeario/skycli#74
- Add default app plan
- Add unique key to app domain column
=> Update gateway db

cmd/auth/main.go, pkg/auth/dependency/provider/password/authdata.go, pkg/auth/dependency/provider/password/mock_password.go, pkg/auth/dependency/provider/password/password.go, pkg/auth/dependency/provider/password/provider.go, pkg/auth/dependency/provider/password/tx_provider.go, pkg/auth/dependency/userprofile/mock_store.go, pkg/auth/dependency/userprofile/store.go, pkg/auth/handler/update_metadata.go, pkg/auth/handler/update_metadata_test.go, pkg/core/auth/authtoken/jwt.go, pkg/core/utils/utils.go, pkg/core/utils/utils_test.go
=> Provide a basic interface for updating metadata

cmd/migrate/main.go, pkg/migrate/command.go
This is for controller setup, controller will call the migration api server to run migration on client auth db
=> Update migration script to support http server mode, allow calling migration command by api request

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
connect #904
This help controller to manage hook with cloud code easier.
=> Add cloud code name to hook in tenant config

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
it seems that it was missed in the previous rename.
=> Rename AUTH_HOOKS to HOOKS

cmd/gateway/main.go, pkg/auth/dependency/hook/executor.go, pkg/auth/handler/signup_test.go, pkg/core/config/tenant.go, pkg/core/http/header.go, pkg/core/inject/inject.go, pkg/core/logging/logging.go, pkg/core/middleware/requestid.go, pkg/core/middleware/tenant_test.go, pkg/core/model/app.go, pkg/gateway/handler/cloudcode.go, pkg/gateway/handler/gear.go, pkg/gateway/inject.go, pkg/gateway/middleware/authinfo.go, pkg/gateway/middleware/inject.go, pkg/gateway/middleware/tenant.go
This PR implements this feature https://github.com/SkygearIO/features/pull/303
=> Gateway auth info

cmd/gateway/main.go, pkg/core/middleware/cors.go
Created `demo` branch in origin for micro-services demo and this PR and this PR is for demo only
=> Hardcode CORS header for demo

pkg/auth/dependency/sso/authinfo.go, pkg/auth/dependency/sso/authinfo_processor.go, pkg/auth/dependency/sso/instagram.go, pkg/auth/dependency/sso/mock_provider.go, pkg/auth/dependency/sso/sso.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/auth_url_test.go, pkg/auth/handler/sso/link_test.go, pkg/auth/handler/sso/login_test.go, pkg/auth/handler/sso/sso.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
=> Implement welcome email destination config

pkg/auth/handler/update_metadata.go, pkg/auth/handler/update_metadata_test.go
=> Make update metadata user ID optional

pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/inject.go
=> Disable anonymous signup

pkg/auth/handler/forgotpwd/reset.go, pkg/auth/handler/sso/iframe_handler.go, pkg/auth/handler/userverify/verify_code.go
=> Add missing method OPTIONS

pkg/auth/handler/change_password.go, pkg/auth/handler/disable.go, pkg/auth/handler/disable_test.go, pkg/auth/handler/forgotpwd/reset.go, pkg/auth/handler/login.go, pkg/auth/handler/logout.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/reset_password_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/sso/customtoken.go, pkg/core/audit/trail.go
=> Rename auth id to user

cmd/auth/main.go, cmd/gateway/main.go
=> Apply RequestID and CORS middleware properly

cmd/gateway/main.go
/healthz should bypass all middleware
=> Fix healthz endpoint of gateway

cmd/auth/main.go, pkg/auth/dependency/hook/deliverer.go, pkg/auth/dependency/hook/deliverer_impl.go, pkg/auth/dependency/hook/deliverer_impl_test.go, pkg/auth/dependency/hook/deliverer_mock.go, pkg/auth/dependency/hook/handler.go, pkg/auth/dependency/hook/provider_impl.go, pkg/auth/dependency/hook/provider_impl_test.go, pkg/auth/dependency/hook/provider_mock.go, pkg/auth/inject.go, pkg/core/http/header.go, pkg/core/inject/inject.go, pkg/core/inject/inject_test.go, pkg/core/middleware/validate_host.go, pkg/core/middleware/validate_host_test.go, pkg/gateway/handler/deployment_route.go, pkg/gateway/handler/gear.go, pkg/gateway/inject.go
=> Handle relative web-hook URL

cmd/gateway/main.go
=> Fix database connection leakage in gateway

cmd/auth/main.go, pkg/auth/handler/change_password.go, pkg/auth/handler/login.go, pkg/auth/handler/refresh.go, pkg/auth/handler/refresh_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/sso/customtoken.go, pkg/auth/handler/sso/sso.go, pkg/auth/model/auth_response.go, pkg/core/auth/session.go, pkg/core/auth/session/expiry.go, pkg/core/auth/session/expiry_test.go, pkg/core/auth/session/provider_impl.go, pkg/core/auth/session/provider_impl_test.go, pkg/core/auth/session/provider_mock.go, pkg/core/auth/session/writer_mock.go
=> Implement refresh token

pkg/auth/inject.go, pkg/core/auth/session.go, pkg/core/auth/session/event_store.go, pkg/core/auth/session/event_store_mock.go, pkg/core/auth/session/provider_impl.go, pkg/core/auth/session/provider_impl_test.go, pkg/core/auth/session/redis/event_store.go, pkg/core/auth/session/redis/keys.go, pkg/core/http/header.go, pkg/gateway/inject.go
=> Implement session access event stream

cmd/auth/main.go, pkg/core/async/executor.go
=> Fix not passing DB pool to task executor

pkg/auth/inject.go, pkg/core/auth/session/redis/store.go, pkg/core/logging/factory.go, pkg/core/middleware/authn.go, pkg/gateway/inject.go
=> Make session error handling more fine-grained

go.mod, go.sum, pkg/core/redis/pool.go
=> Support connecting redis sentinel for session store

pkg/auth/dependency/audit/password_checker.go, pkg/auth/dependency/principal/password/mock_password.go, pkg/auth/dependency/principal/password/password.go, pkg/auth/dependency/principal/password/principal.go, pkg/auth/dependency/principal/password/provider.go, pkg/auth/dependency/principal/password/tx_provider.go, pkg/auth/handler/login.go, pkg/core/password/bcrypt.go, pkg/core/password/bcrypt_sha512.go, pkg/core/password/bcrypt_sha512_test.go, pkg/core/password/bcrypt_test.go, pkg/core/password/dispatch.go, pkg/core/password/dispatch_test.go, pkg/core/password/format.go, pkg/core/password/format_test.go
references:
https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/
https://passlib.readthedocs.io/en/stable/modular_crypt_format.html
=> Fix bcrypt truncates input password

pkg/auth/handler/change_password.go, pkg/auth/handler/login.go, pkg/auth/handler/mfa/authenticate_bearer_token.go, pkg/auth/handler/mfa/authenticate_oob.go, pkg/auth/handler/mfa/authenticate_recovery_code.go, pkg/auth/handler/mfa/authenticate_totp.go, pkg/auth/handler/signup.go, pkg/auth/handler/sso/customtoken.go, pkg/auth/handler/sso/login.go
=> Fix handler error handling

cmd/auth/main.go, cmd/gateway/.env.example, pkg/auth/dependency/userverify/senderfactory.go, pkg/auth/dependency/userverify/test_sender.go, pkg/auth/inject.go, pkg/core/config/default.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go, pkg/core/mail/sender_impl.go, pkg/core/sms/client_impl.go, pkg/core/sms/nexmo.go, pkg/core/sms/twilio.go, pkg/core/validation/schema.go, pkg/core/validation/schema_test.go, pkg/gateway/config/config.go
=> Introduce default SMTP, Twilio and Nexmo Config

cmd/auth/main.go, cmd/gateway/main.go, pkg/core/redis/pool.go
`REDIS_HOST` should not be required if Sentinel is ON, and `REDIS_SENTINEL_ADDRS` is require instead
=> Update redis config checking

pkg/core/handler/authz.go
=> Fix exposing internal error in response

pkg/auth/dependency/sso/facebook.go, pkg/auth/dependency/sso/google.go, pkg/auth/dependency/sso/instagram.go, pkg/auth/dependency/sso/linkedin.go, pkg/auth/dependency/sso/sso.go, pkg/auth/dependency/userverify/senderfactory.go, pkg/auth/dependency/welcemail/sender.go, pkg/auth/handler/signup.go, pkg/auth/handler/sso/auth_handler.go, pkg/auth/handler/sso/customtoken.go, pkg/auth/handler/sso/login.go, pkg/auth/handler/sso/sso.go, pkg/auth/handler/userverify/verify_request.go, pkg/auth/inject.go, pkg/auth/task/send_verify_code.go, pkg/auth/task/send_welcome_email.go
=> Fix missing url prefix

pkg/asset/handler/sign.go, pkg/core/cloudstorage/asset_item.go, pkg/core/cloudstorage/azure.go, pkg/core/cloudstorage/gcs.go, pkg/core/cloudstorage/list_objects_response.go, pkg/core/cloudstorage/mock_provider.go, pkg/core/cloudstorage/provider.go, pkg/core/cloudstorage/provider_impl.go, pkg/core/cloudstorage/s3.go, pkg/core/cloudstorage/sign_request.go, pkg/core/cloudstorage/sign_response.go, pkg/gateway/config/config.go, pkg/gateway/model/app.go, pkg/gateway/model/plan.go
=> Override the expire of signed URL

pkg/asset/handler/presign_upload.go, pkg/asset/handler/presign_upload_form.go, pkg/auth/handler/change_password.go, pkg/auth/handler/disable.go, pkg/auth/handler/logout.go, pkg/auth/handler/me.go, pkg/auth/handler/mfa/delete_authenticator.go, pkg/auth/handler/mfa/list_recovery_code.go, pkg/auth/handler/mfa/regenerate_recovery_code.go, pkg/auth/handler/mfa/revoke_all_bearer_token.go, pkg/auth/handler/reset_password.go, pkg/auth/handler/session/get.go, pkg/auth/handler/session/list.go, pkg/auth/handler/session/revoke.go, pkg/auth/handler/session/revoke_all.go, pkg/auth/handler/sso/link.go, pkg/auth/handler/sso/unlink.go, pkg/auth/handler/update_metadata.go, pkg/auth/handler/userverify/verify_code.go, pkg/auth/handler/userverify/verify_request.go, pkg/core/auth/authz/error.go, pkg/core/auth/authz/policy/authinfo.go, pkg/core/auth/authz/policy/authinfo_test.go, pkg/core/auth/authz/policy/compound_policy.go, pkg/core/auth/authz/policy/disable.go, pkg/core/auth/authz/policy/verified.go, pkg/core/auth/authz/policy/verified_test.go
=> Add policy to check user verified

pkg/core/http/header.go, pkg/core/model/app.go, pkg/core/model/app_test.go
=> Drop support of custom access token header

pkg/auth/dependency/principal/password/login_id.go, pkg/auth/dependency/principal/password/login_id_test.go, pkg/auth/dependency/principal/password/mock_password.go, pkg/auth/dependency/principal/password/password.go, pkg/auth/dependency/principal/password/provider.go, pkg/auth/handler/login.go, pkg/auth/handler/login_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go
=> Validate login ID format

cmd/auth/main.go, pkg/auth/handler/forgotpwd/reset_form.go
=> Fix incorrect schema for reset password page

pkg/auth/dependency/principal/password/principal.go, pkg/auth/handler/change_password_test.go, pkg/auth/handler/login.go, pkg/auth/handler/login_test.go, pkg/auth/handler/logout_test.go, pkg/auth/handler/session/revoke_all_test.go, pkg/auth/handler/session/revoke_test.go, pkg/auth/handler/signup.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/auth_url.go, pkg/auth/handler/sso/auth_url_test.go, pkg/auth/handler/sso/customtoken.go, pkg/auth/handler/sso/login.go, pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Do not expose realm in APIs

pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go
=> Correct Nexmo secret name

pkg/auth/dependency/forgotpwdemail/sender.go, pkg/auth/dependency/userverify/sender.go
=> Make template context values easier to use

pkg/core/logging/logging.go
=> Use new loggers for every requests

pkg/core/name/name.go, pkg/core/name/name_test.go
=> Update app name format

pkg/core/config/schema.go
=> Update UserConfiguration schema to remove legacy fields

pkg/core/auth/session/writer_impl.go
=> Fix max-age calculation

pkg/core/handler/request.go, pkg/core/handler/request_test.go
=> Validate JSON content type leniently

cmd/gateway/main.go, pkg/core/redis/pool.go
=> Return Redis connection to pool properly

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Use SHA256 instead for template item hash

pkg/asset/handler/get.go, pkg/core/http/cors.go, pkg/gateway/handler/deployment_route.go, pkg/gateway/handler/gear.go
=> Improve existing CORS header handling

pkg/core/middleware/validate_host.go, pkg/core/middleware/validate_host_test.go
=> Informational error for invalid hosts

cmd/gateway/main.go, pkg/core/db/pool.go, pkg/gateway/store/pq/store.go
If gateway failed to connect to database (e.g. database container is being initialized in local development flow), it'll failed to start. We should connect to database lazily.
=> Connect to gateway database lazily

pkg/auth/dependency/mfa/authenticator.go, pkg/auth/dependency/mfa/authenticator_test.go, pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Update MFA default maximum count to 99

pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Remove UserVerification ErrorRedirect

pkg/auth/dependency/forgotpwdemail/template.go, pkg/auth/dependency/mfa/template.go, pkg/auth/dependency/userverify/template.go, pkg/auth/dependency/welcemail/template.go
=> Add default HTML template

cmd/auth/Dockerfile
=> Update auth gear docker build to copy reserved name source

go.mod, go.sum, pkg/auth/dependency/principal/password/login_id_checker.go, pkg/auth/dependency/principal/password/login_id_checker_test.go, pkg/auth/dependency/principal/password/mock_store.go, pkg/auth/dependency/principal/password/provider.go, pkg/auth/dependency/principal/password/provider_test.go, pkg/auth/dependency/principal/password/store.go, pkg/auth/inject.go
=> Disallow username with confusing homoglyphs

pkg/gateway/handler/deployment_route.go, pkg/gateway/handler/gear.go, pkg/gateway/handler/reverse_proxy.go
=> Add more context in logging gateway reverse proxy error

pkg/auth/dependency/forgotpwdemail/template.go, pkg/auth/dependency/mfa/sender_impl.go, pkg/auth/dependency/mfa/template.go, pkg/auth/dependency/userverify/template.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Polish template content

pkg/auth/dependency/principal/password/mock_password.go, pkg/auth/handler/forgotpwd/forgot_password.go, pkg/auth/handler/forgotpwd/forgot_password_test.go
=> Use correct email for password recovery email

pkg/auth/dependency/forgotpwdemail/sender.go, pkg/auth/dependency/mfa/sender_impl.go, pkg/auth/inject.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Remove too many AppName overrides

pkg/auth/inject.go, pkg/core/inject/context.go, pkg/core/inject/context_test.go, pkg/core/inject/inject.go, pkg/core/inject/inject_test.go
fix #1172 
NOTE: we may want to revisit our DI system design in future to make these problems easier to notice.
=> Make HookProvider a scoped dependency

pkg/auth/dependency/authnsession/provider_impl.go, pkg/auth/handler/logout.go, pkg/core/auth/session/provider.go, pkg/core/auth/session/provider_impl.go, pkg/core/auth/session/provider_impl_test.go, pkg/core/auth/session/provider_mock.go
=> Fix session event timing

pkg/auth/dependency/principal/oauth/oauth.go
=> Add team ID to provider keys

cmd/auth/main.go, pkg/auth/dependency/principal/password/error.go, pkg/auth/dependency/principal/password/login_id.go, pkg/auth/dependency/principal/password/login_id_test.go, pkg/auth/dependency/principal/password/mock_password.go, pkg/auth/dependency/principal/password/mock_store.go, pkg/auth/dependency/principal/password/password.go, pkg/auth/dependency/principal/password/provider.go, pkg/auth/dependency/principal/password/provider_test.go, pkg/auth/dependency/principal/password/store.go, pkg/auth/dependency/userverify/provider.go, pkg/auth/handler/list_identities.go, pkg/auth/handler/list_identities_test.go, pkg/auth/handler/login.go, pkg/auth/handler/login_test.go, pkg/auth/handler/loginid/add.go, pkg/auth/handler/loginid/add_test.go, pkg/auth/handler/loginid/remove.go, pkg/auth/handler/loginid/remove_test.go, pkg/auth/handler/loginid/update.go, pkg/auth/handler/loginid/update_test.go, pkg/auth/handler/loginid/utils.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/customtoken_test.go, pkg/core/auth/session/provider.go, pkg/core/auth/session/provider_impl.go, pkg/core/auth/session/provider_mock.go, pkg/core/auth/testing/context.go
=> Implement login ID APIs

pkg/core/middleware/cors.go
=> Set CORS max age header

pkg/auth/dependency/sso/apple.go, pkg/auth/dependency/sso/azureadv2.go, pkg/auth/dependency/sso/google.go, pkg/auth/dependency/sso/oauth_provider.go, pkg/auth/dependency/sso/oidc.go, pkg/core/config/tenant.go, pkg/core/config/tenant_test.go
=> Use OIDC for Google SSO login

pkg/asset/inject.go, pkg/auth/dependency/forgotpwdemail/sender.go, pkg/auth/dependency/hook/deliverer_impl.go, pkg/auth/dependency/hook/deliverer_impl_test.go, pkg/auth/dependency/mfa/sender_impl.go, pkg/auth/dependency/sso/oauth_provider.go, pkg/auth/dependency/userverify/codegenerator.go, pkg/auth/dependency/userverify/senderfactory.go, pkg/auth/dependency/welcemail/sender.go, pkg/auth/handler/sso/config.go, pkg/auth/handler/sso/config_test.go, pkg/auth/handler/sso/unlink_test.go, pkg/auth/inject.go, pkg/core/apiclientconfig/provider_impl.go, pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go, pkg/core/db/pool.go, pkg/core/middleware/authn.go, pkg/core/middleware/cors.go, pkg/core/middleware/cors_test.go, pkg/core/middleware/tenant_test.go, pkg/core/sms/client_impl.go, pkg/gateway/inject.go, pkg/gateway/middleware/authinfo.go, standalone-tenant-config.sample.yaml
fix https://github.com/SkygearIO/skygear-server/issues/1190
=> Rename UserConfiguration to AppConfiguration

pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go, standalone-tenant-config.sample.yaml
=> Add version to AppConfiguration

pkg/core/db/context.go, pkg/core/db/error.go, pkg/core/db/sql_executor.go, pkg/core/middleware/recover.go
=> Handle concurrent write conflict

cmd/auth/main.go, migrations/core/1578470800_manual-verification.down.sql, migrations/core/1578470800_manual-verification.up.sql, pkg/auth/dependency/hook/mutator_impl.go, pkg/auth/dependency/hook/mutator_impl_test.go, pkg/auth/dependency/userverify/provider.go, pkg/auth/event/hook_response.go, pkg/auth/event/mutation.go, pkg/auth/event/user_update.go, pkg/auth/handler/change_password_test.go, pkg/auth/handler/login_test.go, pkg/auth/handler/loginid/update_test.go, pkg/auth/handler/signup_test.go, pkg/auth/handler/sso/auth_result_test.go, pkg/auth/handler/sso/customtoken_test.go, pkg/auth/handler/sso/link_test.go, pkg/auth/handler/sso/login_test.go, pkg/auth/handler/update_metadata_test.go, pkg/auth/handler/userverify/update.go, pkg/auth/handler/userverify/update_test.go, pkg/auth/handler/userverify/verify_code.go, pkg/auth/handler/userverify/verify_code_form.go, pkg/auth/model/user.go, pkg/core/auth/authinfo/authinfo.go, pkg/core/auth/authinfo/pq/store.go, pkg/core/auth/authz/policy/verified.go, pkg/gateway/middleware/authinfo.go
=> Update user verification feature

pkg/core/apiversion/apiversion.go, pkg/core/apiversion/apiversion_test.go, pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go, pkg/core/middleware/apiversion.go, pkg/core/middleware/apiversion_test.go, pkg/core/server/option.go, pkg/core/server/server.go, pkg/core/server/server_test.go
=> Rename version to api_version

pkg/core/cloudstorage/presign_upload_request.go, pkg/core/cloudstorage/presign_upload_request_test.go
=> Fix Cache-Control header format

pkg/gateway/handler/deployment_route.go, pkg/gateway/handler/deployment_route_test.go, pkg/gateway/model/deployment_route.go, pkg/gateway/model/route_match.go, pkg/gateway/model/route_match_test.go
=> Update static asset routing

pkg/asset/handler/presign_upload.go, pkg/asset/handler/presign_upload_form.go, pkg/auth/handler/update_metadata.go, pkg/core/auth/authz/policy/compound.go, pkg/core/auth/authz/policy/compound_policy.go, pkg/core/auth/authz/policy/compound_policy_test.go
=> Fix compound authz policy short-circuit behavior

cmd/asset/main.go, pkg/asset/config/config.go, pkg/core/cloudstorage/azure.go
Minio is already supported, and I don't think there's an official GCS emulator.
fix #1205
=> Allow configuring Azure blob storage service URL

pkg/gateway/middleware/app.go, pkg/gateway/middleware/deployment_route.go
=> Simplify gateway error messages

pkg/auth/dependency/sso/apple.go, pkg/auth/dependency/sso/authinfo.go, pkg/auth/dependency/sso/azureadv2.go, pkg/auth/dependency/sso/google.go, pkg/auth/dependency/sso/oidc.go, pkg/auth/dependency/sso/state.go, pkg/auth/handler/sso/auth_handler.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/auth_redirect.go, pkg/core/http/cookie.go
=> Store `nonce` in `state`

migrations/controller/1584062803_update_default_domain.down.sql, migrations/controller/1584062803_update_default_domain.up.sql, pkg/gateway/handler/gateway.go, pkg/gateway/middleware/app.go, pkg/gateway/middleware/app_test.go, pkg/gateway/model/app.go, pkg/gateway/model/domain.go, pkg/gateway/store/mock_store.go, pkg/gateway/store/pq/domain.go, pkg/gateway/store/standalone/standalone.go, pkg/gateway/store/store.go
=> Support default domain

cmd/auth/main.go, go.mod, go.sum, pkg/auth/dependency/authn/provider.go, pkg/auth/dependency/authn/result.go, pkg/auth/dependency/authn/session_provider.go, pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/deps.go, pkg/auth/dependency/webapp/require_anonymous_middleware.go, pkg/auth/dependency/webapp/required_authenticated_middleware.go, pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/validate_provider_impl.go, pkg/auth/dependency/webapp/validate_provider_test.go, pkg/auth/handler/login.go, pkg/auth/handler/mfa/authenticate_bearer_token.go, pkg/auth/handler/mfa/authenticate_oob.go, pkg/auth/handler/mfa/authenticate_recovery_code.go, pkg/auth/handler/mfa/authenticate_totp.go, pkg/auth/handler/mfa/authn.go, pkg/auth/handler/signup.go, pkg/auth/handler/sso/auth_result.go, pkg/auth/handler/sso/link.go, pkg/auth/handler/sso/login.go, pkg/auth/handler/sso/login_test.go, pkg/auth/handler/webapp/settings.go, pkg/auth/handler/webapp/wire.go, pkg/auth/handler/webapp/wire_gen.go, pkg/auth/template/template.go, pkg/core/phone/phone.go, pkg/core/phone/phone_test.go
=> Auth UI Web App - Part 2

pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/redirect.go, pkg/auth/dependency/webapp/redirect_test.go, pkg/auth/dependency/webapp/require_anonymous_middleware.go
With this PR and https://github.com/SkygearIO/skygear-server/pull/1266
OIDC with existing user should work
cc @carmenlau
=> Auth UI Web App - Part 3

pkg/auth/dependency/mfa/cookie.go, pkg/auth/dependency/session/cookie.go, pkg/core/http/cookie.go, pkg/core/http/cookie_test.go
=> Ensure cookie domain is ETLD+1 without port

pkg/auth/dependency/webapp/render_provider_impl.go, pkg/auth/dependency/webapp/template.go, static/authui/css/main.css
=> Fix Auth UI Web App Bugs

pkg/auth/dependency/auth/session_middleware.go, pkg/core/db/context.go, pkg/core/db/context_test.go, pkg/core/db/mock_context.go
=> Refactor TxContext

pkg/auth/dependency/sso/facebook.go, pkg/core/config/tenant.go
fix #1298
I have tested with a test facebook app.
=> Update facebook RP to use v6.0 Graph API

pkg/auth/dependency/authn/provider.go, pkg/auth/dependency/authn/session_provider.go
=> Store MFA bearer token while stepping thru authn session

pkg/auth/dependency/principal/error.go, pkg/auth/handler/sso/unlink.go, pkg/auth/handler/sso/unlink_test.go
=> Unlink not found oauth identity

docs/authn.md
Please let me know if you found any important detail is missing.
ref #1314
=> Add docs on authn and OIDC implementation

pkg/auth/dependency/webapp/render_provider_impl.go, pkg/auth/dependency/webapp/render_provider_test.go, pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/translation.go, pkg/auth/deps.go
=> Show "or" when there are oauth AND login_id

pkg/auth/dependency/oauth/handler/result_authz.go
require #1325 
refs #1334 
See commit dae84bc
This is workaround for fixing ios version < 13.4 that fails to redirect back to the app after signin with apple in auth ui. We will update sdk to provide params by checking the os version. Not sure if this is a good idea to have such custom response mode, or any better idea?
=> Use html meta tag / js to redirect result after authorization in oidc authorize endpoint

pkg/auth/dependency/webapp/template.go, pkg/auth/template/template.go, pkg/core/template/engine.go, pkg/core/template/engine_test.go, pkg/core/template/template_spec.go
=> Support component template

pkg/auth/dependency/webapp/template.go
=> Show correct login ID in enter password page

pkg/auth/handler/webapp/login.go, pkg/auth/handler/webapp/login_password.go, pkg/auth/handler/webapp/logout.go, pkg/auth/handler/webapp/signup.go, pkg/auth/handler/webapp/signup_password.go, pkg/auth/handler/webapp/sso_callback.go, pkg/auth/handler/webapp/wire_gen.go
=> Wrap web app handlers in txn

pkg/auth/dependency/webapp/template.go
=> Ensure all buttons have explicit type

pkg/core/config/authentication.go, pkg/core/config/authenticator.go, pkg/core/config/schema.go, pkg/core/config/tenant.go, pkg/core/config/tenant_test.go, pkg/core/marshal/marshal.go, pkg/core/marshal/marshal_test.go
- omitempty for email and sms message config
- don't `omitempty` for  `secondary_authenticators`, `null` has different meanings in `secondary_authenticators`
=> Update app config serialization setting

static/authui/css/main.css
The sign up link in login page has different color than other links :(
=> Fix inconsistent link color

pkg/core/config/tenant.go
=> Make email the first default login ID

static/authui/css/main.css
=> Prevent Safari iOS from zooming

pkg/auth/dependency/identity/oauth/identity.go, pkg/auth/dependency/identity/oauth/provider.go, pkg/auth/dependency/identity/oauth/store.go, pkg/auth/dependency/interaction/adaptors/identity.go, pkg/auth/dependency/interaction/flows/auth_api_sso.go, pkg/auth/dependency/interaction/flows/webapp_sso.go, pkg/auth/dependency/interaction/interaction.go, pkg/auth/dependency/interaction/provider.go, pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/dependency/interaction/provider_intent.go, pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/handler/sso/auth_handler.go, pkg/auth/handler/sso/auth_handler_test.go, pkg/auth/handler/sso/auth_result.go, pkg/auth/handler/sso/auth_result_test.go, pkg/auth/handler/sso/login.go, pkg/auth/handler/sso/login_test.go, pkg/auth/handler/sso/wire.go, pkg/auth/handler/sso/wire_gen.go
require #1361 
Basics sso interaction integration
Todo:
- handle OnUserDuplicateMerge
=> Use interaction for sso signin

pkg/auth/dependency/identity/oauth/identity.go
=> Correct OAuth provider keys

pkg/auth/dependency/sso/access_token.go, pkg/auth/dependency/sso/authinfo.go, pkg/auth/dependency/sso/google.go, pkg/auth/dependency/sso/linkedin.go, pkg/auth/dependency/sso/userinfo.go
=> Use LinkedIn V2 API to fetch user info

pkg/auth/dependency/identity/loginid/provider.go, pkg/auth/dependency/identity/loginid/store.go, pkg/auth/dependency/interaction/adaptors/identity.go, pkg/auth/dependency/interaction/flows/auth_api.go, pkg/auth/dependency/interaction/flows/interaction.go, pkg/auth/dependency/interaction/provider_action.go, pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/dependency/interaction/provider_intent.go, pkg/auth/dependency/interaction/provider_state.go, pkg/auth/handler/loginid/add.go, pkg/auth/handler/loginid/update.go, pkg/auth/handler/loginid/update_test.go, pkg/auth/handler/loginid/utils.go, pkg/auth/handler/loginid/utils_test.go, pkg/auth/handler/loginid/wire.go, pkg/auth/handler/loginid/wire_gen.go
require #1392 
refs #1374 
Completed:
- Update identity interaction
- Integrate update login id api
- Trigger create and delete identity event in interaction
Discussion:
- The original update login api trigger create and delete identity event, should we update to have one update identity event instead?
=> Interaction update identity

pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/event/identity_update.go
=> Add identity update event

cmd/auth/main.go, pkg/auth/dependency/interaction/flows/webapp.go, pkg/auth/dependency/interaction/state.go, pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/redirect.go, pkg/auth/dependency/webapp/redirect_test.go, pkg/auth/dependency/webapp/state.go, pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/translation.go, pkg/auth/dependency/webapp/validate_provider_impl.go, pkg/auth/handler/webapp/create_password.go, pkg/auth/handler/webapp/enter_login_id.go, pkg/auth/handler/webapp/login.go, pkg/auth/handler/webapp/settings_identity.go, pkg/auth/handler/webapp/wire.go, pkg/auth/handler/webapp/wire_gen.go, pkg/auth/template/template.go, static/authui/css/main.css
=> Identity settings - Part 2

pkg/auth/dependency/webapp/deps.go, pkg/auth/dependency/webapp/render_provider_impl.go, pkg/auth/dependency/webapp/template.go
=> Show forgot password link only when password is enabled

cmd/auth/main.go, static/authui/css/main.css
=> Fix various web app bugs

pkg/auth/handler/list_identities.go, pkg/auth/handler/list_identities_test.go, pkg/auth/handler/wire.go, pkg/auth/handler/wire_gen.go
=> Update using identity provider for list identity api

.travis.yml, Makefile, devtools/devtools.go, go.mod, go.sum, pkg/auth/handler/oauth/challenge.go
=> Fix API doc builds

pkg/auth/dependency/identity/loginid/provider.go, pkg/auth/dependency/identity/loginid/store.go, pkg/auth/dependency/identity/oauth/provider.go, pkg/auth/dependency/identity/provider/provider.go, pkg/auth/dependency/identity/provider/provider_mock_test.go, pkg/auth/dependency/interaction/provider.go, pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/dependency/interaction/provider_flow_test.go, pkg/auth/dependency/interaction/provider_mock_test.go
=> Fix duplicate user checking

pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/translation.go
=> Translate more error

cmd/auth/main.go, pkg/auth/handler/session/resolve.go
=> Do not validate host for resolve endpoint

pkg/auth/dependency/identity/info.go
=> Mask internal identity claims

pkg/auth/dependency/webapp/template.go, static/authui/css/main.css
=> Fix UI glitches related to user input

pkg/auth/dependency/webapp/render_provider_impl.go, pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/translation.go, pkg/auth/dependency/webapp/validate_provider_impl.go, pkg/auth/dependency/webapp/validate_provider_test.go
=> Support input type email

static/authui/css/main.css
=> Set logo aspect ratio to be 21:9

cmd/auth/main.go
=> Fix access key not resolved in resolve endpoint

pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/validate_provider_impl.go
=> Fix not handling OAuth errors

static/authui/js/main.js
=> Allow only one form submission

pkg/auth/dependency/webapp/state.go, pkg/auth/dependency/webapp/state_provider.go, pkg/auth/dependency/webapp/state_provider_test.go, pkg/auth/dependency/webapp/state_test.go
=> Clear state error on form changes

pkg/auth/dependency/authenticator/oob/deps.go, pkg/auth/dependency/authenticator/oob/provider.go
=> Fix missing template context fields

pkg/auth/dependency/identity/anonymous/request.go, pkg/auth/dependency/sso/oidc.go, pkg/core/jwt/claims.go, pkg/core/jwt/claims_test.go
ref #1482 
we may want to see if v4 of the JWT library supports handling time drifts.
=> Do not validate iat for JWT

pkg/auth/dependency/webapp/template.go
=> Do not need to use value to preserve form fields

pkg/auth/dependency/identity/loginid/provider.go, pkg/auth/dependency/identity/provider/provider.go, pkg/auth/dependency/identity/provider/provider_mock_test.go, pkg/auth/dependency/interaction/provider.go, pkg/auth/dependency/interaction/provider_commit.go, pkg/auth/dependency/interaction/provider_flow_test.go, pkg/auth/dependency/interaction/provider_intent.go, pkg/auth/dependency/interaction/provider_mock_test.go, pkg/auth/dependency/webapp/authenticate_provider_impl.go, pkg/auth/dependency/webapp/template.go
=> Use type=tel for digit input

pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/webapp/translation.go, static/authui/js/main.js
=> Do not show 0s for cooldown label

pkg/auth/dependency/webapp/template.go, static/authui/js/main.js
=> Work around PRG pattern and back stack problem

static/authui/js/main.js
=> Make form submission to more align with spec

pkg/auth/dependency/authenticator/oob/deps.go, pkg/auth/dependency/authenticator/oob/provider.go, pkg/auth/dependency/forgotpassword/deps.go, pkg/auth/dependency/forgotpassword/provider.go, pkg/auth/dependency/webapp/render_provider_impl.go, pkg/auth/dependency/webapp/template.go, pkg/auth/dependency/welcomemessage/deps.go, pkg/auth/dependency/welcomemessage/provider.go, pkg/auth/handler/oauth/wire_gen.go, pkg/auth/handler/webapp/wire_gen.go, pkg/core/config/auth_ui.go, pkg/core/config/auth_ui_gen.go, pkg/core/config/schema.go, pkg/core/config/schema_test.go, pkg/core/config/tenant.go, pkg/core/config/tenant_gen.go, pkg/core/config/tenant_test.go
=> Add metadata configuration

pkg/auth/dependency/oauth/handler/handler_authz.go, pkg/auth/dependency/oauth/handler/handler_authz_test.go, pkg/auth/dependency/oauth/handler/handler_token.go, pkg/auth/dependency/oauth/handler/response_mode.go, pkg/auth/dependency/oauth/handler/response_mode_test.go, pkg/auth/dependency/oauth/handler/result_authz.go, pkg/auth/dependency/oauth/metadata.go, pkg/auth/dependency/oauth/protocol/authz.go, pkg/core/url/fragment.go, pkg/core/url/fragment_test.go, static/authui/js/main.js
=> OAuth response mode
